var filterStruct=[{"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Pupil-Teacher Ratio","Tooltip":"40 students per teacher, considering all teachers"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Drinking water facility available and functional"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Toilets available and fuctional","Tooltip":"40 students per functional toilet and urinal"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Separate toilets available for girls"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Mid day meal provided"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Functional School Kitchen"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Teaching learning material distributed"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"All-weather building"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Office cum Head teacher's room"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Library Available"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Playground Available"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Uniform distributed"},
				  {"Area":"RTE Indicators", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"School development Plan submitted"},
				  {"Area":"RTE Indicators", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"0-3/4-6/7-9/10-13/All","Indicator":"Composite RtE Rating","Tooltip":"Summation of the 13 RtE indicators mapped"},
				  {"Area":"Attendance", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"< 30 %/31-50%/51-80%/>80%/All","Indicator":"% of girls attendance on the day of visit"},
				  {"Area":"Attendance", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"< 30 %/31-50%/51-80%/>80%/All","Indicator":"% of boys attendance on the day of visit"},
				  {"Area":"Attendance", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"< 30 %/31-50%/51-80%/>80%/All","Indicator":"% of attendance on the day of visit"},
				  {"Area":"Adequacy of teacher", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"< 30 %/31-50%/51-80%/>80%/All","Indicator":"% of teachers (full and partime) present on the day of visit"},
				  {"Area":"Adequacy of teacher", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"<50%/50-80%/80-99%/100%/All","Indicator":"% of sanctioned teachers appointed"},
				  {"Area":"Adequacy of teacher", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"<50%/50-80%/80-99%/100%/All","Indicator":"% of teachers attended/attending in-service training"},
				  {"Area":"Adequacy of teacher", "Icon":"red.png/green.png/blank.png","Legend":"Not Available/Available/All","Indicator":"Special counsellors for CWSN in school/circle"},
				  {"Area":"Adequacy of teacher", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Pupil-Teacher Ratio","Tooltip":"40 students per teacher, considering all teachers"},
				  {"Area":"Adequacy of teacher", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Pupil-Teacher Ratio (permanent teachers)","Tooltip":"40 students per teacher, considering only PERMANENT teachers"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"No facility/School Handpump/Tap inside the school/Pond/All","Indicator":"Primary source of drinking water facility"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All", "Indicator":"Drinking water facility available and functional"},
				  {"Area":"WASH infrastructure", "Icon":"yellow.png/red.png/green.png/blank.png","Legend":"No/Unsafe/Safe/All", "Indicator":"Drinking water tested"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/yellow.png/green.png/blank.png","Legend":"Not Available/Non-functional/Functional/All", "Indicator":"Toilet availability","Tooltip":"Whether a toilet is avialable and is functional"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Toilets adequacy","Tooltip":"40 students per functional toilet and urinal"},
				  {"Area":"WASH infrastructure", "Icon":"green.png/red.png/blank.png","Legend":"No/Yes/All", "Indicator":"Toilets locked and inaccessible to students"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/green.png/yellow.png/blank.png","Legend":"No/Yes/No Toilet/All", "Indicator":"Handwashing facility available near the toilet"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/blue.png/green.png/yellow.png/blank.png","Legend":"No doors/Doors present but broken/Doors (enough to provide privacy)/No Toilet/All", "Indicator":"Doors available in toilets"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/green.png/blue.png/yellow.png/blank.png","Legend":"Yes/No/Could not observe toilets/No Toilet/All", "Indicator":"Is there urine/feaces on the floor/seat/walls/etc. of the toilet"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"Not Available/1-3/4-5/> 5/All", "Indicator":"Separate toilets for female teachers"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"Not Available/1-3/4-5/> 5/All", "Indicator":"Separate toilets for male teachers"},
				  {"Area":"WASH infrastructure", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"Not Available/1-3/4-5/> 5/All", "Indicator":"Separate toilets for teachers"},
				  {"Area":"School Management", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"School Management Committee constituted"},
				  {"Area":"School Management", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"School development Plan submitted"},
				  {"Area":"School Management", "Icon":"red.png/yellow.png/blue.png/green.png/blank.png","Legend":"0/1-5/6-10/> 10/All", "Indicator":"Number of MTA conducted in the last 12 months"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"New school building funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Additional classroom funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Sanitation facilities/toilets funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Drinking water facilities funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Library funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Incinerator funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Teaching learning material funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"Maintenance funds"},
				  {"Area":"School Funds", "Icon":"red.png/green.png/blank.png","Legend":"No/Yes/All","Indicator":"School Development grant funds"}
				  
				  ];